language: node_js
node_js:
- "6"
- "node"
services:
- docker
before_install:
- echo $TRAVIS_BRANCH
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
  # Updating NPM to relevant version >= 3 on Node.JS LTS
- npm i -g npm@^3
script:
- echo $TRAVIS_BRANCH
- npm run lint
- npm test
- npm run build:docker
sudo: required
addons:
  apt:
    packages:
    - sshpass
after_success:
- echo $TRAVIS_BRANCH
- mv dist $TRAVIS_BRANCH
- mkdir build
- cp -r $TRAVIS_BRANCH ./build/
- tar -czf build.tgz build
- export SSHPASS=$DEPLOY_PASS
- sshpass -e scp -o stricthostkeychecking=no build.tgz $DEPLOY_USER@$DEPLOY_HOST:./

after_error:
- echo $TRAVIS_BRANCH
- mv dist $TRAVIS_BRANCH
- mkdir build
- cp -r $TRAVIS_BRANCH ./build/
- tar -czf build.tgz build
- export SSHPASS=$DEPLOY_PASS
- sshpass -e scp -o stricthostkeychecking=no build.tgz $DEPLOY_USER@$DEPLOY_HOST:./
